### PR TITLE
Capitalise

### PR DESCRIPTION
**Pull request by ger619**
- Check the usage of [Decorator pattern in Ruby](https://refactoring.guru/design-patterns/decorator/ruby/example#example-0)
- Think about how you can use two decorators in order to capitalize and trim people's names.
- In the following steps you will get instructions for implementing the Decorator design pattern for this case.

Interface

**Create a class Nameable.**

- Implement a method called correct_name that will raise a NotImplementedError.

**Turn your Person class to Nameable**

- Make sure that your Person class inherits from Nameable
- Make sure that this class has a method correct_name implemented. It should simply return the name attribute.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @ger619, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Professional Readme
✔️ Correct gitflow
✔️ All linters passing

## Required 
- [ ] Kindly make sure to add a file name "`Gemfile`" and add the below lines in it.
```
source 'https://rubygems.org'

# gem "rails"

gem 'rubocop', '>= 1.0', '< 2.0'
```
After adding this make sure to run `bundle install`.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ger619** [comment]
Hello @sja-thedude please expain further what is needed? I have not understood you.

**Comment by sja-thedude** [comment]
> Hello @sja-thedude please expain further what is needed? I have not understood you.
> 
> 

Hi @ger619, You basically have to add a Gemfile which is required for Ruby projects. So just add a file named "Gemfile" and add the lines given above. And then run bundle install.

**Comment by ger619** [comment]
@sja-thedude thanks. I just noticed my mistake. it is my third week and no one had mentioned it. Have a blessed day

**Comment by ger619** [comment]
> > Hello @sja-thedude please expain further what is needed? I have not understood you.
> 
> Hi @ger619, You basically have to add a Gemfile which is required for Ruby projects. So just add a file named "Gemfile" and add the lines given above. And then run bundle install.

@sja-thedude thanks. I just noticed my mistake. it is my third week and no one had mentioned it. Have a blessed day

**Review by rustam-tolipov — APPROVED** [review]
## Hello @ger619👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

Developer-512px-10

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
